# Generated by Django 5.2.6 on 2025-10-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='renew_count',
            field=models.IntegerField(default=0),
        ),
    ]
