# Generated by Django 5.2.6 on 2026-02-06 20:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0002_borrowrecord_renew_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
