# Generated by Django 5.2.6 on 2025-10-09 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10)),
                ('role', models.CharField(choices=[('user', 'user'), ('librarian', 'librarian')], default='user', max_length=10)),
                ('membership_level', models.CharField(choices=[('basic', 'Cơ bản'), ('standard', 'Tiêu chuẩn'), ('premium', 'Cao cấp')], default='basic', max_length=15)),
                ('membership_upgrade_date', models.DateField(blank=True, null=True, verbose_name='Ngày nâng cấp')),
                ('membership_expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
